AWSTemplateFormatVersion: "2010-09-09"

Description: ECR Repositories

Resources:
    TodobackendRepository:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryName: docker-in-aws/todobackend
