AWSTemplateFormatVersion: "2010-09-09"

Description: Todobackend Application

Parameters:
    ApplicationDesiredCount:
        Type: Number
        Description: Desired EC2 instance count
    ApplicationImageId:
        Type: String
        Description: ECS Amazon Machine Image (AMI) ID
    ApplicationSubnets:
        Type: List<AWS::EC2::Subnet::Id>
        Description: Target subnets for EC2 instances

Resources:
    ApplicationAutoscalingLaunchConfiguration:
        Type: AWS::AutoScaling::LaunchConfiguration
        Metadata:
            AWS::CloudFormation::Init:
                config:
                    commands:
                        05_public_volume:
                            command: mkdir -p /data/public
                        06_public_volume_permissions:
                            command: chown R 1000:1000 /data/public
                        10_first_run:
                            command: sh firstrun.sh
                            cwd: /home/ec2-user
                            env:
                                ECS_CLUSTER: !Ref ApplicationCluster
                                STACK_NAME: !Ref AWS::StackName
                                AUTOSCALING_GROUP: ApplicationAutoscaling
                                AWS_DEFAULT_REGION: !Ref AWS::Region
        Properties:
            ImageId: !Ref ApplicationImageId
            InstanceType: t2.micro
            KeyName: admin
            IamInstanceProfile: !Ref ApplicationAutoscalingInstanceProfile
            SecurityGroups:
                - !Ref ApplicationAutoscalingSecurityGroup
            UserData:
                Fn::Base64:
                    Fn::Sub: |
                        #!/bin/bash
                        /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} \
                            --resource ApplicationAutoscalingLaunchConfiguration \
                            --region ${AWS::Region}
                        /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} \
                            --resource ApplicationAutoscaling \
                            --region ${AWS::Region}
    ApplicationCluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: todobackend-cluster
    ApplicationAutoscaling:
        Type: AWS::AutoScaling::
        CreationPolicy:
            Count: !Ref ApplicationDesiredCount
            Timeout: PT15M
        Properties:
            LaunchConfigurationName: !Ref ApplicationAutoscalingLaunchConfiguration
            MinSize: 0
            MaxSize: 4
            DesiredCapacity: !Ref ApplicationDesiredCount
            VPCZoneIdentifier: !Ref ApplicationSubnets
            Tags:
                - Key: Name
                  Value: !Sub ${AWS::StackName}-ApplicationAutoscaling-instance
                  PropagateAtLaunch: "true"
